### ISSUE TITLE
Github handle

### ISSUE THREAD

**Issue by BramVanPevenage** [XpiritCommunityEvents/HOL#5]
BramVanPevenage

**Comment by DennisThie** [comment]
done

**Comment by DennisThie** [comment]
Hi @BramVanPevenage , je hebt nog wel een openstaande invite voor deze org. Wil je deze accepteren? Je kunt hem vinden in je e-mail of via de volgende link: https://github.com/orgs/XpiritCommunityEvents/invitation (wel even inloggen)

**Comment by DennisThie** [comment]
👍
